### PR TITLE
[Beginner][Translate] User Rights Management Document to english md

### PR DESCRIPTION
**Pull request by enkilee**
* https://github.com/OpenTenBase/OpenTenBase/issues/37
Create 07-user-rights-en.md
fix 07-user-rights.md

### CODE REVIEW

**Comment by JackLau1222** [comment]
there is already exist 07-user-rights.en.md,please fix the 07-user-rights.en.md rather than create a new 07-user-rights-en.md,thanks for your contribution

**Comment by bartdong** [comment]
> there is already exist 07-user-rights.en.md,please fix the 07-user-rights.en.md rather than create a new 07-user-rights-en.md,thanks for your contribution

Agree with Jack. Please check and fix it @enkilee

**Comment by enkilee** [comment]
> > there is already exist 07-user-rights.en.md,please fix the 07-user-rights.en.md rather than create a new 07-user-rights-en.md,thanks for your contribution
> 
> Agree with Jack. Please check and fix it @enkilee Thank you :)

OK .
*https://github.com/OpenTenBase/docs/pull/20

**Comment by enkilee** [comment]
So I close this PR.

**Pull request closed without merging**
